- name: (Ubuntu) Setup Desktop + XRDP (no Avica)
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 xrdp curl jq unzip
          sudo apt-get install -y xfconf
          
          # Create user + password
          sudo useradd -m -s /bin/bash Bullettemporary || true
          echo "Bullettemporary:Bullet@12345" | sudo chpasswd
          echo "Bullettemporary ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/bullettemporary
          
          # Fix XFCE black screen / failsafe session
          sudo systemctl enable dbus
          sudo systemctl start dbus
          echo "export XDG_CONFIG_DIRS=/etc/xdg:/etc" | sudo tee -a /etc/environment
          echo "startxfce4" | sudo tee /home/Bullettemporary/.xsession
          sudo chown Bullettemporary:Bullettemporary /home/Bullettemporary/.xsession
          
          # Force xrdp to start xfce
          sudo sed -i '/^test -x.*startwm.sh/s/^/#/' /etc/xrdp/startwm.sh
          echo "xfce4-session" | sudo tee -a /etc/xrdp/startwm.sh
          
          # Enable XRDP
          sudo systemctl enable xrdp
          sudo systemctl restart xrdp
          
          echo "✅ Ubuntu XFCE Desktop + XRDP ready."
